linters:
  # Disable all linters.
  # Default: false
  # disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - depguard
    - errcheck
    - errname
    - exhaustive
    - exhaustruct
    - makezero
    - gocritic
    - decorder
  disable:
    - unused

# golangci-lint config
linters-settings:
  decorder:
    # Required order of `type`, `const`, `var` and `func` declarations inside a file.
    # Default: types before constants before variables before functions.
    dec-order:
      - var
      - type
      - const
      - func
    # If true, underscore vars (vars with "_" as the name) will be ignored at all checks
    # Default: false (underscore vars are not ignored)
    ignore-underscore-vars: false
    # If true, order of declarations is not checked at all.
    # Default: true (disabled)
    disable-dec-order-check: false
    # If true, `init` func can be anywhere in file (does not have to be declared before all other functions).
    # Default: true (disabled)
    disable-init-func-first-check: false
    # If true, multiple global `type`, `const` and `var` declarations are allowed.
    # Default: true (disabled)
    disable-dec-num-check: false
    # If true, type declarations will be ignored for dec num check
    # Default: false (type statements are not ignored)
    disable-type-dec-num-check: false
    # If true, const declarations will be ignored for dec num check
    # Default: false (const statements are not ignored)
    disable-const-dec-num-check: false
    # If true, var declarations will be ignored for dec num check
    # Default: false (var statements are not ignored)
    disable-var-dec-num-check: false
  makezero:
    # Allow only slices initialized with a length of zero.
    # Default: false
    always: true
  depguard:
    rules:
      org_deps:
        # list-mode: lax # allow unless explicitely denied
        files:
          - "**/apps/**"
          - "**/entity/**"
          - "!$test"
        allow:
          - $gostd
          - github.com/qzich/orgserv

  