version: "3.5"
services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
        ALLOW_EMPTY_PASSWORD: yes
        MYSQL_DATABASE: users
        MYSQL_ROOT_PASSWORD: roo
    volumes:
     - mysql_data:/var/lib/mysql

volumes:
 mysql_data: